alumno/urls.py
from django.urls import path
from . import views


app_name = 'alumnos'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),

]

home/urls.py
from django.urls import path
from home import views

urlpatterns = [
    #path('prueba/', views.prueba, name='prueba'),
    path('index.html', views.Inicio, name="Inicio"),
]

study_helper/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from home.views import Home, Acerca, Contacto
from profesor.views import listar_profesores
from materia.views import Materias,registrarCurso
from aula_virtual.views import Chat, ChatInternoAula

#from materia.views import views
#from aula_virtual.views import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home, name="Home"),
    path('about.html', Acerca, name="Acerca"),
    path('trainers.html', listar_profesores, name="Profesor"),
    path('courses.html', Materias, name="Cursos"),
    path('chat.html', Chat, name="Chat"),
    path('contact.html', Contacto, name="Contacto"),
    path('registrarCurso/', registrarCurso, name="registrarCurso"),
    path('chat_interno_aula.html/', ChatInternoAula, name="Chat_interno_aula"),
    path('alumno/', include(('alumno.urls', 'alumno'), namespace='alumno')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <!-- ======= Breadcrumbs ======= -->
    <!-- ======= Testimonials Section ======= -->
    <section id="testimonials" class="testimonials" style="margin-top: 150px;">
      <div class="container" data-aos="fade-up">

        <div id="section-title" style="margin-top: 20px;">
          <h2>El grupo</h2>
          <p>Quienes somos</p>
        </div>

        <div class="testimonials-slider swiper" data-aos="fade-up" data-aos-delay="100">
          <div class="swiper-wrapper">

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial-item">
                  <img src="{% static 'assets/img/testimonials/Thamy_Gonzalez.jpg' %}" class="testimonial-img" alt="">
                  <h3>Thamy Gonzalez</h3>
                  <h4>Testing</h4>
                  <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    Export tempor illum tamen malis malis eram quae irure esse labore quem cillum quid cillum eram malis quorum velit fore eram velit sunt aliqua noster fugiat irure amet legam anim culpa.
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                  </p>
                </div>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial-item">
                  <img src="{% static 'assets/img/testimonials/facu_otero.jpg' %}" class="testimonial-img" alt="">
                  <h3>Facundo Otero</h3>
                  <h4>Backend</h4>
                  <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    Enim nisi quem export duis labore cillum quae magna enim sint quorum nulla quem veniam duis minim tempor labore quem eram duis noster aute amet eram fore quis sint minim.
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                  </p>
                </div>
              </div>
            </div><!-- End testimonial item -->            

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial-item">
                  <img src="{% static 'assets/img/testimonials/Mauri_Gonzalez.jpg' %}" class="testimonial-img" alt="">
                  <h3>Mauricio Gonzalez</h3>
                  <h4>Frontend</h4>
                  <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    Quis quorum aliqua sint quem legam fore sunt eram irure aliqua veniam tempor noster veniam enim culpa labore duis sunt culpa nulla illum cillum fugiat legam esse veniam culpa fore nisi cillum quid.
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                  </p>
                </div>
              </div>
            </div>

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial-item">
                  <img src="{% static 'assets/img/testimonials/Evelyn_Riascos.jpg' %}" class="testimonial-img" alt="">
                  <h3>Evelin Riascos</h3>
                  <h4>Backend</h4>
                  <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    Quis quorum aliqua sint quem legam fore sunt eram irure aliqua veniam tempor noster veniam enim culpa labore duis sunt culpa nulla illum cillum fugiat legam esse veniam culpa fore nisi cillum quid.
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                  </p>
                </div>
              </div>
            </div>

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial-item">
                  <img src="{% static 'assets/img/testimonials/Joaquin_Sanchez.jpg' %}" class="testimonial-img" alt="">
                  <h3>Joaquin Sanchez</h3>
                  <h4>UX</h4>
                  <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    Fugiat enim eram quae cillum dolore dolor amet nulla culpa multos export minim fugiat minim velit minim dolor enim duis veniam ipsum anim magna sunt elit fore quem dolore labore illum veniam.
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                  </p>
                </div>
              </div>
            </div>           

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial-item">
                  <img src="{% static 'assets/img/testimonials/Facu_Lanza.jpg' %}" class="testimonial-img" alt="">
                  <h3>Facundo Lanza</h3>
                  <h4>Full-Stack</h4>
                  <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    Fugiat enim eram quae cillum dolore dolor amet nulla culpa multos export minim fugiat minim velit minim dolor enim duis veniam ipsum anim magna sunt elit fore quem dolore labore illum veniam.
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                  </p>
                </div>
              </div>
            </div>

           

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial-item">
                  <img src="{% static 'assets/img/testimonials/Jennifer_Durrling.jpg' %}" class="testimonial-img" alt="">
                  <h3>Jennifer Durrling</h3>
                  <h4>Team Leader</h4>
                  <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    Fugiat enim eram quae cillum dolore dolor amet nulla culpa multos export minim fugiat minim velit minim dolor enim duis veniam ipsum anim magna sunt elit fore quem dolore labore illum veniam.
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                  </p>
                </div>
              </div>
            </div>



            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial-item">
                  <img src="{% static 'assets/img/testimonials/David_Hernandez.jpg' %}" class="testimonial-img" alt="">
                  <h3>Issac D</h3>
                  <h4>Backend</h4>
                  <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    Fugiat enim eram quae cillum dolore dolor amet nulla culpa multos export minim fugiat minim velit minim dolor enim duis veniam ipsum anim magna sunt elit fore quem dolore labore illum veniam.
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                  </p>
                </div>
              </div>
            </div><!-- End testimonial item -->

            <!-- End testimonial item -->

          </div>
          <div class="swiper-pagination"></div>
        </div>

      </div>
    </section><!-- End Testimonials Section -->

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
{% load static %}
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Study Helper</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

</head>

<body style="background-image: url({% static 'assets/img/Background.svg' %});background-size: cover;">

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

  
      <h1 class="logo me-auto"><a href="{% url 'Home' %}"><img src="{% static 'assets/img/logo_conTXT.svg' %}" alt="inicio" /></a></h1>
      
      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
         <li><a href="{% url 'Home' %}">Inicio</a></li>
         <li><a href="{% url 'Acerca' %}">Acerca Nuestro</a></li>
         <li><a href="{% url 'Cursos' %}">Cursos</a></li>
         <li><a href="{% url 'Profesor' %}">Profesores</a></li>          
         <li><a href="{% url 'Chat' %}">Aula Virtual</a></li>  
         <li><a href="{% url 'Contacto' %}">Contacto</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
     
    </div>
    
  </header><!-- End Header -->

  <main id="main" style="margin-top:110px;">

{% block content %}

{% endblock %}
    
  </main><!-- End #main -->

<!-- ======= Footer ======= -->

<footer id="footer">

    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright" style="margin: 16px 0px ;">
          &copy; Copyright © 2023 Study Helper. <strong><span>c14-44-n-python</span></strong>. <br> Todos los derechos reservados
      </div>
      <div style="margin: 16px 0px ;">
        Política de privacidad | Aviso legal | Mapa del sitio.
    </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/chat-confirm.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container" id="chat">
        <h1>Aulas Virtuales</h1>
        <form method="post">{% csrf_token %}
            ¿Estás seguro que deseas borrar el curso "{{ object }}"?
            <input type="submit" value="Submit" />
        </form>
    </div>

    
{% endblock %}

templates/chat-detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container" id="chat">
    <h1>Bienvenido al aula: {{aula.nombre}}</h1>
    <p>programada para la fecha: {{aula.fecha}}</p>
    <p>
        <a href="{% url 'List' %}">Regresar a lista</a>
    </p>
    
</div>

    
{% endblock %}

templates/chat-form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container" id="chat">
        <h1>Aulas Virtuales</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Enviar" />
        </form>
    </div>

    
{% endblock %}

templates/chat.html
{% extends "base.html" %}
{% load static %}

{% block content %}
   
    
    {% for aula in lista %}
    <section id="popular-courses" class="cursos mb-5" data-aos="fade-up">
      <div class="container">
        <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4 mt-md-0" style="margin: auto;width: initial;">
          <div class="teacher-item">
            <img src="{% static 'assets/img/course1.jpg' %}" class="img-fluid" alt="...">
              <div class="teacher-content card-content">
              <div class="bg_oscuro">
                <h4 style="margin: 40px auto;">Bienvenido al aula de {{aula.nombre}}</h4>                
                <h5>Profesor Elegido:</h5>
                <p>{{aula.id_profesor}}</p>
                <a href="{% url 'Chat_interno_aula' %}"><button style="margin:auto;" type="button" class="btn btn-success">Ir a sala de consulta</button></a>              
                <h5>Fecha estipulada para la clase</h5>
                <p>{{aula.fecha}}</p>
                <h5>Material de estudio</h5>
                <p>{{aula.material}}</p>
                <div style="margin: 40px auto;" class="trainer d-flex justify-content-between align-items-center">
                  <a href="{% url 'Chat_interno_aula' %}"><button style="margin:auto;" type="button" class="btn btn-success">Ir a sala de consulta</button></a>
                </div>
              
              
              </div>
          </div>
        </div>
              
      </div>
    {% endfor %}
  
    
{% endblock %}

templates/contact.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs" data-aos="fade-in">
      <div class="container">
        <h2>Contacto</h2>
        <p>Est dolorum ut non facere possimus quibusdam eligendi voluptatem. Quia id aut similique quia voluptas sit quaerat debitis. Rerum omnis ipsam aperiam consequatur laboriosam nemo harum praesentium. </p>
      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      

      <div class="container" data-aos="fade-up">

        <div class="row mt-5">        

          <div class="col-lg-12 mt-5 mt-lg-0" style="background-color:#fff;padding:20px; text-align: center;">

            <form action="forms/contact.php" method="post" role="form" class="php-email-form">
              <div class="row">
                <div class="col-md-6 form-group">
                  <input type="text" name="name" class="form-control" id="name" placeholder="Nombre" required>
                </div>
                <div class="col-md-6 form-group mt-3 mt-md-0">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Email" required>
                </div>
              </div>
              <div class="form-group mt-3">
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Título" required>
              </div>
              <div class="form-group mt-3">
                <textarea class="form-control" name="message" rows="5" placeholder="Mensaje" required></textarea>
              </div>
              <div class="my-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Tu mensaje ha sido enviado. Gracias!</div>
              </div>
              <div class="text-center"><button type="submit">Enviar mensaje</button></div>
            </form>

          </div>

        </div>

      </div>
    </section><!-- End Contact Section -->

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex justify-content-center align-items-center">
    <div class="container position-relative" data-aos="fade-right" data-aos-delay="100">
      <h1>Bienvenido a <br>STUDY HELPER</h1>
      <h2>¡Aprendamos algo nuevo juntos!</h2>
      <div style="margin-top: 40px;">
        <a href="{% url 'alumno:login' %}" class="get-started-btn">Iniciar</a>
        <a href="{% url 'alumno:signup' %}" class="get-started-btn">Registro</a>
    </div>
    </div>
    
  

  </section>     

<!-- ======= Counts Section ======= -->
    <section id="counts" class="counts section-bg">
      <div class="container">

        <div class="row counters">

          <div class="col-lg-3 col-6 text-center">
            <span data-purecounter-start="0" data-purecounter-end="1232" data-purecounter-duration="1" class="purecounter"></span>
            <p>Estudiantes</p>
          </div>

          <div class="col-lg-3 col-6 text-center">
            <span data-purecounter-start="0" data-purecounter-end="64" data-purecounter-duration="1" class="purecounter"></span>
            <p>Cursos</p>
          </div>
    
          <!-- <div class="col-lg-3 col-6 text-center">
            <span data-purecounter-start="0" data-purecounter-end="42" data-purecounter-duration="1" class="purecounter"></span>
            <p>Events</p>
          -->
       
  

          <div class="col-lg-3 col-6 text-center">
            <span data-purecounter-start="0" data-purecounter-end="166" data-purecounter-duration="1" class="purecounter"></span>
            <p>Campus Virtuales</p>
          </div>

          <div class="col-lg-3 col-6 text-center">
            <span data-purecounter-start="0" data-purecounter-end="15" data-purecounter-duration="1" class="purecounter"></span>
            <p>Profesores</p>
          </div>



      </div>
    </section><!-- End Counts Section -->

    

    <!-- ======= Find teacher Section ======= -->
    <section id="popular-teacher" class="teacher" data-aos="fade-up">
      <div class="container" >

        <div class="section-title">
          <h2 id="title_teacher">Encuentra un profesor que se adapte a tus necesidades</h2>
         
        </div>

          <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4 mt-md-0" style="margin: auto;
          width: initial;">
            <div class="teacher-item">
              <img src="{% static 'assets/img/teacher1.jpg' %}" class="img-fluid" alt="...">
              <div class="teacher-content card-content">
                <div class="d-flex justify-content-between align-items-center mb-3">
                </div>

                <h3>Profesores Particulares</h3>
                <p>Aprende a tu ritmo y con atención personalizada. <br>
                  Con las clases particulares en línea de nuestra app, podrás aprender lo que quieras, cuando quieras y donde quieras. Encuentra a un profesor para cualquier materia, nivel o objetivo. Nuestra plataforma te permite conectarte con los mejores profesores, que te ayudarán a alcanzar tus metas educativas.</p>
                <div class="trainer d-flex justify-content-between align-items-center">
              
                <h4 style="border-radius: 4px; display: flex; ">Ver más</h4>

                </div>
              </div>
            </div>
          </div> <!-- End teacher Item-->
        
        {% if profesores %}
          <div style="display: flex;  justify-content: space-between; margin: 40px 0px 40px 0px;" >
            {% for profesor in profesores %}
              <div class="teacher-presentation" style="display: block; text-align: center;">
                <!– 
                 imagen profesor
                 –>
                  <h5 style="margin-top: 8px;">{{ profesor.first_name }} {{ profesor.last_name }}</h5>
                  <p>{{ profesor.materia }}</p>
              </div>
            {% endfor %}
          </div>
        {% endif %}
         

    </section><!-- End find teacher Section -->

    <!-- ======= Find course Section ======= -->
<section id="popular-course" class="course">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2 id="title_course">Adquiere métodos efectivos de aprendizaje  
          </h2>
          
        </div>

          <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4 mt-md-0" style="margin: auto;
          width: initial;">
            <div class="course-item">
              <img src="{% static 'assets/img/course1.jpg' %}"  class="img-fluid" alt="...">
              <div class="course-content card-content">
                <div class="d-flex justify-content-between align-items-center mb-3">
                </div>

                <h3>Cursos</h3>
                <p>Descubre un mundo nuevo de posibilidades. Logra superarte en cada nuevo desafío. Nosotros te ayudamos!</p>
                <div class="trainer d-flex justify-content-between align-items-center">
              
                <h4 style="border-radius: 4px; display: flex; ">Ver más</h4>

                </div>
              </div>
            </div>
          </div> <!-- End course Item-->

      </div>
    </section><!-- End find course Section -->

 <!-- ======= Find comunity Section ======= -->
 <section id="popular-comunity" class="comunity">
  <div class="container" data-aos="fade-up">

    <div class="section-title">
      <h2 id="title_comunity">Comparte material de estudio con la comunidad
      </h2>
      
    </div>

      <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4 mt-md-0" style="margin: auto;
      width: initial;">
        <div class="comunity-item">
          <img src="{% static 'assets/img/comunity1.png' %}"  class="img-fluid" alt="...">
          <div class="comunity-content card-content">
            <div class="d-flex justify-content-between align-items-center mb-3">
            </div>

            <h3>Foro</h3>
            <p>Un espacio para aprender, compartir y colaborar. <br>

            <h6>Una herramienta valiosa ya que ofrece un espacio donde los usuarios pueden conectar con otros, compartir conocimiento y aprender de los demás.</h6> <br>
            <ul>
             <li> Material educativo: Los usuarios pueden compartir recursos educativos, como libros, artículos, vídeos, etc. Esto puede ser muy útil para los usuarios que buscan información sobre un tema específico. </li>
              
             <li> Consultas: Los usuarios pueden hacer preguntas a otros usuarios o a los moderadores del foro. Esto puede ser una forma eficaz de resolver dudas o dificultades. </li>
              
             <li> Colaboración: Los usuarios pueden trabajar juntos en proyectos o tareas. Esto puede ser una forma divertida y motivadora de aprender.</li>

            </ul>
            <div class="trainer d-flex justify-content-between align-items-center">
          
            <h4 style="border-radius: 4px; display: flex; ">Ver más</h4>

            </div>
          </div>
        </div>
      </div> <!-- End course Item-->

  </div>
  
</section><!-- End find course Section -->

<!-- ======= Testimonials Section ======= -->


<div class="testimonials">  


  
  
<div class="card text-bg-dark" style="width: 32%; height: 40px;
margin: 24px; display: table; border-radius: 16px;">
  <img src="{% static 'assets/img/marcos.jpg' %}" class="card-img" alt="...">
  <div class="card-img-overlay">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    <p class="card-text"><small>Last updated 3 mins ago</small></p>
  </div>
</div>
<div class="card text-bg-dark" style="width: 32%; height: 40px;
margin: 24px; display: table; border-radius: 16px;">
  <img src="{% static 'assets/img/laura.jpg' %}" class="card-img" alt="...">
  <div class="card-img-overlay">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    <p class="card-text"><small>Last updated 3 mins ago</small></p>
  </div>
</div>




</div>

<!-- End Testimonials Section -->
  
{% endblock %}

  

templates/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <!-- ======= Breadcrumbs ======= -->
    <div>
      <img class="container" src="assets/img/Logo.svg" style= "width: 150px;display: block;" alt="">         
      <h2 class="container" style="display: flex;flex-direction: row;flex-wrap: nowrap; margin-top: 40px; font-weight: 600; color:#212529 ;">Iniciar Sesion</h2> 
    </div> <!-- End Breadcrumbs -->

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
  
      <div class="container" data-aos="fade-up" style="padding: 8px;">

        <div class="row mt-5">       

          <div class="col-lg-12 mt-5 mt-lg-0" style="padding:20px; text-align: center;">
            
            <form action="{% url 'alumno:login' %}" method="post" role="form">
              {% csrf_token %}
              <div class="form-group mt-3">
                  <input type="text" name="username" class="form-control" id="usuario" placeholder="Usuario" required>
              </div>
              <div class="form-group mt-3">
                <input type="password" class="form-control" name="password" id="password" placeholder="Contraseña" required>
              </div>
              <div class="text-center mt-3"><button name="send" type="submit">Ingresar</button></div>
              <div class="text-center my-3"><a href="recover-password.html"><u>Recuperar contraseña</u></a></div>
            </form>

          </div>

        </div>

      </div>
    </section><!-- End Contact Section -->

{% endblock %}

templates/registro.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <!-- ======= Breadcrumbs ======= -->
    <div>
    <img class="container" src="assets/img/Logo.svg" style= "width: 150px; display: block; background-size:contain; " alt="">         
    <h2 class="container" style="display: flex;flex-direction: row;flex-wrap: nowrap; margin-top: 40px; font-weight: 600; color:#212529; justify-content: center;">Registro</h2> </div>
   <!-- End Breadcrumbs -->

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      
      <div class="container" data-aos="fade-up" style="padding: 8px;">

        <div class="row mt-5">        

          <div class="col-lg-12 mt-5 mt-lg-0" style=padding:20px; text-align: center;">

            <form action="{% url 'alumno:signup' %}" method="post" role="form">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-6 form-group">
                  <input type="name" class="form-control" name="first_name" id="name" placeholder="Nombre y apellido" required>
                </div>
                <div class="col-md-6 form-group">
                  <input type="text" name="username" class="form-control" id="username" placeholder="Usuario" required>
                </div>
              </div>

              <div class="row">
                <div class="col-md-6 form-group">
                  <input type="text" name="tipo_documento" class="form-control" id="tipodoc" placeholder="Tipo Documento" required>
                </div>
                <div class="col-md-6 form-group">
                  <input type="text" name="num_documento" class="form-control" id="nrodoc" placeholder="Nro Documento" required>
                </div>
              </div>

              <div class="row">                
                <div class="col-md-6 form-group">
                  <input type="telefono" class="form-control" name="phone_number" id="telefono" placeholder="Télefono" required>
                </div>
                <div class="col-md-6 form-group">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Correo electrónico" required>
                </div>
              </div>

              <div class="row">                
                <div class="col-md-6 form-group">
                  <input type="password" class="form-control" name="password1" id="password" placeholder="Contraseña" required>
                </div>
                <div class="col-md-6 form-group">
                  <input type="password" class="form-control" name="password2" id="ConfPassword" placeholder="Confirmar contraseña" required>
                </div>
              </div>

              <div class="text-center"><button type="submit">Enviar</button>
                
              </div>
            </form>

          </div>

        </div>

      </div>
    </section><!-- End Contact Section -->

{% endblock %}